server:
  port: 5000
spring:
  application:
    name: gateway-server
  # cloud:
  #   gateway:
  #     routes:
  #       - id: booking-service
  #         uri: http://localhost:5005
  #         predicates:
  #           - Path=/msapi/bookings/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka

