spring.application.name=booking-service



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/booking_salondb
spring.datasource.username=root
spring.datasource.password=5820

server.port= 5005