spring.application.name=service-offering


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/service_offering_salondb
spring.datasource.username=root
spring.datasource.password=5820

server.port= 5004